# Netlify configuration file

[build]
  publish = "public" # Directory containing your static files
  command = "npm run build" # Command to build your project (if applicable)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Optional: Specify functions directory if you have serverless functions
[functions]
  directory = "api" # Directory containing your serverless functions
